### ISSUE TITLE
macOS 10.13.6 failed building the package showing missed define: NUMPY_IMPORT_ARRAY_RETVAL

### ISSUE THREAD

**Issue by sunlightxhw** [groupeLIAMG/ttcr#32]
Hello, thank you for sharing this package.
I've installed numpy, python,vtk, cython. when I built the package, it failed because lack of definition of a macro. the terminal print is like this:
ttcrpy/Grid2Dttcr.cpp:535:9: error: use of undeclared identifier 'NUMPY_IMPORT_ARRAY_RETVAL'
            import_array_throw();  // to use PyArray_SimpleNewFromData
I am fresh with python. What should I do?
Much appreciated!

**Comment by bernard-giroux** [comment]
Hi,

Thanks for your email.  I would need to know which OS you are using, as well as the version of python & numpy version you are running.

**Comment by sunlightxhw** [comment]
the versions are macOS 10.13.6, Python 3.8.3, numpy 1.19.0.
I used command pip install ttcrpy to install the package, then encountered the problems above.
Thank you very much!

**Comment by bernard-giroux** [comment]
Can you pull master and try again?

**Comment by sunlightxhw** [comment]
Hello, I tried pip install ttcrpy, but same error appeared.
I will try download package and build later. thank you very much.

**Comment by bernard-giroux** [comment]
I haven’t built the wheels, so yes, please try the master branch.  Thanks

**Comment by sunlightxhw** [comment]
Hello, I have built standalone command line tool successfully with VTK9.0. Thank you very much.

**Comment by bernard-giroux** [comment]
Thanks.  I will update the wheels.
