### ISSUE TITLE
Raytracing reflections

### ISSUE THREAD

**Issue by pasansherath** [groupeLIAMG/ttcr#33]
Hi there,
I am interested in using this code. It looks awesome as it can be run with python. I looked at the two examples. I was wondering whether it can trace only refractions. Is it possible to trace reflections as well?

Thanks
Pasan

**Comment by bernard-giroux** [comment]
Hi Pasan,
It's possible but not straight-forward and has to be done in multiple steps.  You have to store arrival times at all nodes on the surface defining your reflection interface, and use those as source on a subsequent run.  It can become tedious when you have many interfaces, and if you want multiples...
