### ISSUE TITLE
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

### ISSUE THREAD

**Issue by tgautam03** [groupeLIAMG/ttcr#38]
Hi

I just installed ttcrpy using pip and when I try to run the simple examples notebook, I get an error while importing tmesh.

I hope someone can help me with this.

**Comment by maherNsr** [comment]
Hi;
Try to install a more recent version of numpy (1.20.0 for example).  To do that, reinstall numpy by successively running these 2 lines in a terminal:
pip uninstall numpy
pip install numpy

On Apr 15, 2021, at 7:39 AM, Tushar03 ***@***.******@***.***>> wrote:


Attention : ce courriel provient d'un expéditeur externe.



Hi

I just installed ttcrpy using pip and when I try to run the simple examples notebook, I get an error while importing tmesh.

I hope someone can help me with this.

**Comment by bernard-giroux** [comment]
@tgautam03   Did upgrading bumpy solve the problem?  If not, what is the error message?

Thanks

**Comment by bernard-giroux** [comment]
No answer: closing issue

**Comment by tgautam03** [comment]
Sorry, I didn't receive the email regarding the fix. 

Yes, I tried reinstalling numpy and facing the same issue.
