### ISSUE TITLE
example2.py - gmsh problem?

### ISSUE THREAD

**Issue by sdkatvt** [groupeLIAMG/ttcr#52]
I have the following issue with example2.py, example1.py runs fine. This seems to be a gmsh issue. I have the latest gmsh installed.

python example2.py
Info    : Clearing all models and views...
Info    : Done clearing all models and views
Info    : Meshing 1D...
Info    : [  0%] Meshing curve 10 (Nurb)
Info    : [ 20%] Meshing curve 11 (Line)
Info    : [ 30%] Meshing curve 12 (Nurb)
Info    : [ 50%] Meshing curve 13 (Line)
Info    : [ 60%] Meshing curve 14 (Line)
Info    : [ 80%] Meshing curve 15 (Line)
Info    : [ 90%] Meshing curve 16 (Line)
Info    : Done meshing 1D (Wall 0.00973982s, CPU 0.009607s)
Info    : Meshing 2D...
Info    : [  0%] Meshing surface 31 (Plane, Frontal-Delaunay)
Info    : [ 50%] Meshing surface 32 (Plane, Frontal-Delaunay)
Info    : Done meshing 2D (Wall 0.0669393s, CPU 0.065739s)
Info    : 2390 nodes 4929 elements
Traceback (most recent call last):
  File "example2.py", line 94, in <module>
    node, _ = gmsh.model.mesh.getNode(tag)
ValueError: too many values to unpack (expected 2)

**Comment by bernard-giroux** [comment]
Now fixed with last commit
