### ISSUE TITLE
Compute reflections

### ISSUE THREAD

**Issue by jddorellanao** [groupeLIAMG/ttcr#54]
I just saw this [issue](https://github.com/groupeLIAMG/ttcr/issues/33), I am interested in making a ray tracing for 3D seismic acquisition purposes, something like [this](https://academic.oup.com/view-large/figure/31540957/179-1-201-fig015.jpeg), and could you give an example of the code, or the steps, to carry out the reflections, it is not for a complex model, my idea is to do it on a flat layered model. 

Thanks in advance.

**Comment by bernard-giroux** [comment]
Look at example2 notebook in the example folder.  It is a 2D case, but the procedure is the same in 3D.
