### ISSUE TITLE
A way to get travel time tables from matlab?

### ISSUE THREAD

**Issue by tshadoan** [groupeLIAMG/ttcr#56]
Hello, 

I am trying to use TTCR to get travel-time tables from source locations along a rectangular grid. I have been able to get raypaths and sensitivity kernel using the matlab codes provided. I am not too familiar with Python and C++; I am wondering if there is a way from Matlab to get extract that information.

**Comment by bernard-giroux** [comment]
Sorry but what do you mean by travel time table?

**Comment by bernard-giroux** [comment]
This has net been implemented in Matlab, sorry.  I am no longer investing time in the Matlab wrappers, but you could dig in the source code and do it, that's what open source is for...
