### ISSUE TITLE
Quick questions

### ISSUE THREAD

**Issue by Timothy-Xia** [groupeLIAMG/ttcr#58]
Hi!
I a graduate student at UT austin. I have couples of questions about this work.
1. Can it deal with a steep velocity change (such as 1.5μs/mm and 4μs/mm)? Reclinear grids with second order don't work in this circumstance. I saw your papers, your meshing can be refined at the boundary of two medium.
2. Does this matlab with c++ scripts are the same as python scripts?

**Comment by bernard-giroux** [comment]
Hi

1. the SPM method is better suited for this kind of model (make sure you don't use the option to compute traveltimes from raypaths).
2. not all functionalities are implemented in matlab.  I no longer devote time to the matlab codebase, except for minimal maintenance...

**Comment by Timothy-Xia** [comment]
Thank you so much for the reply.



Bernard Giroux ***@***.***> 于2023年5月2日周二 12:37写道：
