### ISSUE TITLE
Irregular grid size support

### ISSUE THREAD

**Issue by SquirrelKnight** [groupeLIAMG/ttcr#60]
Hello,

I was wondering if you can/will add any functionality for irregular grid sizes to Grid3d. For example, I am working with data that has a finer vertical velocity which are homogeneous horizontally across the layers. The 1-D vertical spacing starts out at 10 (meters), which increases with depth until there is 200 meter spacing. For the horizontal spacing, I would like to set it at a higher interval, such as 50 meters. These nodes reflect changes in speed within the water column, and I am computing the travel-time of acoustic waves from a transducer to a transponder.

When trying to use an irregular grid with the current code I get this message: "FSM: Grid cells must be cubic".

I wasn't sure if this would be a more suitable problem to the Mesh3d module, but the example provided does not seem to work with the current version of pygmsh, and I am at a bit of a loss for where to start...

**Comment by bernard-giroux** [comment]
Hi,

You don't have the cubic cell restriction with the SPM or DSPM (although I did not test it much in terms of accuracy).  

I think that pygmsh has been abandoned since python support has been incorporated in gmsh (I should update the example...).

**Comment by SquirrelKnight** [comment]
Hi @bernard-giroux . Thanks for the quick response. I tried out DSPM. It looks like I don't need cubic cells any longer, however it still doesn't work with differently spaced Z cells (e.g. 0, 5, 10, 20, 30, 50). The program assumes that the difference in Z is the difference between the first pair of Z values (in this case 5), and so raytracing for a point at a Z of 45 comes up with an 'outside grid' error. In this case, I believe the program would think the grid ends at 25. I'm not sure if this would be too complicated to implement, or even very applicable to other cases.

FSM is also significantly faster when comparing computations on identical grids, but I suppose that's to be expected.

**Comment by bernard-giroux** [comment]
Can you share code excerpts that allows reproducing this?  I might have some time in the upcoming days to look at it.

**Comment by SquirrelKnight** [comment]
@bernard-giroux Here is the code I have written to test with some of my data. I have also included the data files as attachments. Note that you will need Pandas for loading the CSV files with the way the code is currently setup.

`import ttcrpy.rgrid as rg
import ttcrpy.tmesh as tm
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import pandas as pd
import configparser

x_int = 50
y_int = 50
z_int = 50

vmod_file = 'GNSSA-03.2022_1-syn-svp.csv'
vmod_df = pd.read_csv(vmod_file)

# Interpolate depths and velocities
depths = np.arange(0-z_int,vmod_df.depth.max()+z_int,z_int)
vels = np.interp(depths,vmod_df.depth.values,vmod_df.speed.values)

# Don't interpolate depths and velocities
# depths = vmod_df.depth.values
# vels = vmod_df.speed.values

# Load geodesy observations
df = pd.read_csv('GNSSA-03.2021_1-obs_sub.csv',low_memory=False)
df['ant_u0'] = -df['ant_u0']
df['ant_u1'] = -df['ant_u1']
station_list = df.MT.unique()

revised_data = pd.DataFrame()


cfg_file = 'GNSSA-03.2021_1-initcfg.csv'
config = configparser.ConfigParser()
config.read(cfg_file)

# Load site name
site = config['Obs-parameter']['site_name']

# Get survey date
date = config['Obs-parameter']['Date(UTC)']

# Load center coordinates
lat0 = float(config['Site-parameter']['latitude0'])
lon0 = float(config['Site-parameter']['longitude0'])
height0 = float(config['Site-parameter']['height0'])
center_E, center_N, center_U = np.array(config['Site-parameter']['center_ENU'].split()).astype('float')
dcentpos_e, dcentpos_n, dcentpos_u, dcentpos_sig_e, dcentpos_sig_n, dcentpos_sig_u, dcentpos_cov_e, dcentpos_cov_n, dcentpos_cov_u = np.array(config['Model-parameter']['dCentPos'].split()).astype('float')
stations = config['Site-parameter']['stations'].split()
# lat, lon, depth = pymap3d.enu2geodetic(center_E,center_N,center_U,lat0,lon0,height0)
all_station_params = []
for i,station in enumerate(stations):
	station_params = config['Model-parameter'][station.lower()+'_dpos'].split()
	station_params.insert(0,station)
	all_station_params.append(station_params)
all_station_params = np.array(all_station_params)
station_df = pd.DataFrame(all_station_params,columns=['sta','E','N','U','sig_E','sig_N','sig_U','cov_NU','cov_UE','cov_EN'])
station_df[['E','N','U']] = station_df[['E','N','U']].astype(float)

# Get vmod bounds
if df.ant_e0.min() <= df.ant_e1.min():
	min_x = int(df.ant_e0.min() - x_int)
else:
	min_x = int(df.ant_e1.min() - x_int)
	
if df.ant_e0.max() >= df.ant_e1.max():
	max_x = int(df.ant_e0.max() + x_int)
else:
	max_x = int(df.ant_e1.max() + x_int)
	
if df.ant_n0.min() <= df.ant_n1.min():
	min_y = int(df.ant_n0.min() - y_int)
else:
	min_y = int(df.ant_n1.min() - y_int)
	
if df.ant_n0.max() >= df.ant_n1.max():
	max_y = int(df.ant_n0.max() + y_int)
else:
	max_y = int(df.ant_n1.max() + y_int)

xs = np.arange(min_x,max_x,x_int).astype(float)
ys = np.arange(min_y,max_y,y_int).astype(float)

# fill in model
V = np.empty((xs.size, ys.size, depths.size))
for n in range(depths.size):
    V[:, :, n] = vels[n]


# Testing the Vmodel
row = df.iloc[1]
src = np.reshape(row[['ant_e0','ant_n0','ant_u0']].values.astype(float),(-1,3))
src2 = np.reshape(row[['ant_e1','ant_n1','ant_u1']].values.astype(float),(-1,3))

dpos = station_df[['E','N','U']].iloc[0]
dpos.U = -dpos.U
dpos = np.reshape(dpos.values,(-1,3))
# dpos = np.array([[300.,300.,300.]]) # Test position

grid = rg.Grid3d(xs,ys,depths,cell_slowness=False,method='FSM') # FSM, SPM, or DSPM
# grid = tm.Mesh3d(np.array([xs,ys,depths]),cell_slowness=False)
slowness = 1./V

tt1, rays1 = grid.raytrace(src,dpos,slowness,return_rays=True)
tt2, rays2 = grid.raytrace(src2,dpos,slowness,return_rays=True)

tt_diff = row.TT - (tt1 + tt2)

print('Difference between observed and estimated travel times: '+str(tt_diff))

# Computes travel times for every grid node
# grid.get_grid_traveltimes()`

[GNSSA-03.2022_1-obs_sub.csv](https://github.com/groupeLIAMG/ttcr/files/11888003/GNSSA-03.2022_1-obs_sub.csv)
[GNSSA-03.2022_1-syn-svp.csv](https://github.com/groupeLIAMG/ttcr/files/11888004/GNSSA-03.2022_1-syn-svp.csv)
[GNSSA-03.2022_1-initcfg.csv](https://github.com/groupeLIAMG/ttcr/files/11888008/GNSSA-03.2022_1-initcfg.csv)

**Comment by bernard-giroux** [comment]
Hi,

Actually, non constant spacing is not currently implemented for grids, sorry.  What is possible is to use a different dy, dy, or dz...   I'd like to implement non constant spacing, but it will take some time.

The short term solution is to use tetrahedral meshes.  Example 2 has been updated to use gmsh, perhaps you can have a look at this one to see the sequence of commands to create the mesh.

**Comment by SquirrelKnight** [comment]
Hi @bernard-giroux. I have followed your advice and am currently working on adapting your code for example 2 to work with my velocity structure. Because I am using a 3d model, I have hit a bit of a snag. I understand we want to have the 4 nodes forming a tetrahedra, as opposed to the 3 nodes forming a triangle, which you have as:
`        for n in range(len(elemTags[0])):
            t = elemNodeTags[0][3*n:(3*n+3)]
            triangles.append(t)
`
For this snippet of code, would you simply change it to this?
`        for n in range(len(elemTags[0])):
            t = elemNodeTags[0][3*n:(3*n+4)]
            tetra.append(t)
`
or should the other 3s be replaced with 4s as well?

Thanks for you patience!

**Comment by bernard-giroux** [comment]
I think that the other 3s should be replaced as well, best way to know it to test it...  I'm on vacation until July 25.  I'll have more time when I get back.  Cheers

**Comment by SquirrelKnight** [comment]
@bernard-giroux Thanks! I appreciate your time. I have figured out that the 4s are indeed the best way to do things. I am going to upload to you the script I have made so far; it uses the same input files as the previous example. 

The takes the layers of my 3d velocity model and extrapolates them across 100x100 meters in X and Y directions. I use the mesh recombination algorithm from gmsh to create tetrahedra (as opposed to triangles), but I'm not sure if this step is even really necessary. Whether perform recombination or not, the program seems to hang indefinitely on the raypath step, so I am likely still doing something wrong. I have noticed that the mesh.get_grid_traveltimes() does not seem to work with Mesh3d, even in much simpler velocity models

Have a good vacation; I'll be doing so myself right about when you are getting back!
[ray_gmsh.txt](https://github.com/groupeLIAMG/ttcr/files/12044062/ray_gmsh.txt)

**Comment by SquirrelKnight** [comment]
@bernard-giroux I've just started looking into things again. It looks like a major issue is created by building the mesh from several rectangles (in 2D) or cubes (in 3D). 

For example, my code uses the addCube function for each layer of the velocity model. When raytracing within the first velocity layer, I have no difficulty getting an output traveltime or raypath. When setting either the source or the receiver in within a depth range of the second layer, the program either hangs or crashes.

I have subsequently created a singular cube model, that linearly interpolates velocity for each node based on the depth. Using this method, I have not come across any issues, so I have some nicely functional code, at the moment, and can compute the two-way travel-time for over 10,000 points in about a minute.

So, I have identified the source of the problem, but not really why. I'm a bit perplexed because the input to Mesh2d or 3d simply uses the 2d numpy arrays. I've checked to see that the triangle values correspond to node indices, and there doesn't seem to be any problem there. Could the source of the problem have to do with abrupt reconfigurations of the triangles for each layer within the grid?

What's your opinion?

**Comment by bernard-giroux** [comment]
@SquirrelKnight Sorry for the long silence.  It's hard to see what could be the problem, I'm not sure what addCube function you refer to...

**Comment by SquirrelKnight** [comment]
Hi @bernard-giroux. I think I mistakenly referred to gmsh.model.occ.addBox as addCube! I've found other ways of working around the issue (manually creating layered boxes and assigning interpolated velocities to each node), but it is interesting that nodes generated for gmsh cubes don't seem to be fully compatible with ttcrpy.
