### ISSUE TITLE
ModuleNotFoundError 

### ISSUE THREAD

**Issue by mg07f** [groupeLIAMG/ttcr#64]
Hi,

I was trying to run your example 1 and got an error message:

ModuleNotFoundError                       Traceback (most recent call last)
Cell In[1], line 9
      6 plt.style.use('seaborn-paper')
      7 plt.rc('font', **{'family': 'sans-serif', 'sans-serif': ['Helvetica']})
----> 9 from ttcrpy.rgrid import Grid3d

File src\\ttcrpy\\rgrid.pyx:28, in init ttcrpy.rgrid()

ModuleNotFoundError: No module named 'vtk'

I run the code on Jupyter Notebook, and version of ttcrypy is 1.2.2, numpy is 1.24.3.

**Comment by bernard-giroux** [comment]
You need to install vtk on your system
