### ISSUE TITLE
bad allocation when calculating L use grid.raytrace(srcs, rcv, slowness,  compute_L=True) for second time

### ISSUE THREAD

**Issue by xiehoulin** [groupeLIAMG/ttcr#69]
I used a  simple method to renew the velocity by calculating the L and the diffrence between the tobs with tcal ,however bad allocation error will happen  when  renewd the gridient  and  calculate L for  the second time by  using grid.raytrace(srcs, rcv, slowness,  compute_L=True) .

**Comment by xiehoulin** [comment]
[codes.zip](https://github.com/groupeLIAMG/ttcr/files/15307938/codes.zip)

**Comment by bernard-giroux** [comment]
I quickly run your code.  You definitely need to apply smoothing constraints, you get a model with values on velocity in the 1e6 range after 1 iteration.  This is an inversion problem, not a raytracing problem.

**Comment by xiehoulin** [comment]
Thank you for your answer professor -Giroux , its truly an inversion problem,I want to renew the velocity by closing to Tobs picked up from frist wave ,raytracing is the main step. you mean that I must control V or slowness_input( in a normal range) while raytracing,or it will repeat calculating in grid.raytrace，which leads to bad allocation?

**Comment by xiehoulin** [comment]
@bernard-giroux Thank you for your answer professor -giroux , its truly an inversion problem,I want to renew the velocity by closing to Tobs picked up from frist wave ,raytracing is the main step. you mean that I must control V or slowness_input( in a normal range) while raytracing,or it will repeat calculating in grid.raytrace，which leads to bad allocation?

**Comment by bernard-giroux** [comment]
ttcrpy is not an inversion package and this is not the place to discuss inversion problems.  I will only suggest that you read about regularization.
