### ISSUE TITLE
Discussion during calculating the rays  in 3D model

### ISSUE THREAD

**Issue by xiehoulin** [groupeLIAMG/ttcr#71]
@bernard-giroux 
Dear Professor Bernard Giroux , I would like to understand the reasons for the difference in calculation time for a pair of symmetric sensors, as well as the reasons for the sawtooth phenomenon in the path.
![b11e2a5d73af0a6f514a13fd1114be2](https://github.com/groupeLIAMG/ttcr/assets/113980101/d9135c61-3d6c-4936-9097-3ecff8aa60d2)

**Comment by bernard-giroux** [comment]
Did you visualize your velocity model to make sure it is OK?  What cell size are you using?  2D or 3D? rectilinear or unstructured?  Which method (SPM, DSPM, FSM)?

**Comment by xiehoulin** [comment]
![ea8a5b7005672652b4338aa3d8f26cf](https://github.com/groupeLIAMG/ttcr/assets/113980101/3c00e691-abb9-403a-ba98-20efd5bf1c41)
![微信图片_20240625105226](https://github.com/groupeLIAMG/ttcr/assets/113980101/80b9a750-f8e8-4c0b-86ee-f1b6e8829154)
![微信图片_20240625105229](https://github.com/groupeLIAMG/ttcr/assets/113980101/a9686494-568c-425c-b61f-63f94b82246a)
Dear Professor Bernard Giroux ,there seems to be no problem with the visualization model. It is a simple 3D model, with the blue area in the middle representing the excavated tunnel and using the default tetrahedral mesh. Three methods have been tried, and the symmetrical arrangement of sensors mentioned above will result in differences and the formation of jagged paths

**Comment by bernard-giroux** [comment]
What method are you using.  You must have a very strong velocity contrast.  Are you defining slowness at nodes or cells? You get this kind of result with the SPM?

**Comment by xiehoulin** [comment]
yes， i use he SPM to calculate travel time  considering diffraction in tunnel voids after defining slowness at nodes

**Comment by bernard-giroux** [comment]
With the SPM, raypaths go throught the nodes of the mesh.  If you have a low density of nodes, you likely end up with the kind of trajectory we see in your results.  The solution would be to increase the number of secondary nodes and/or decrease the size of the tetrahedra at the rock/tunnel boundary.

**Comment by bernard-giroux** [comment]
Also, can you confirm that you have defined velocity for cells, not at nodes?  For models like yours, I would definitively use a model with velocity assigned to cells, not nodes.

**Comment by xiehoulin** [comment]
Yes, thank you for your reply Professor Bernard Giroux. After using grid = rg.Grid3d(X, Y, Z, cell_slowness=True, n_threads=3, method='DSPM', nsnx =10,nsny =10,nsnz =10, n_secondary=5, n_tertiary=5), the paths at both ends of the tunnel have become symmetrical, but there is still sawtooth phenomenon. If I want to solve this problem, do I still need to reduce the mesh size of the tunnel boundary? Can different sizes of grids designed in this 3D be found in ttcrpy documentation file? Or is the accuracy sufficient in this situation?
![微信图片_20240627223349](https://github.com/groupeLIAMG/ttcr/assets/113980101/fbf5ef3b-47bc-4e5c-9412-c54a0abd964c)

**Comment by bernard-giroux** [comment]
You are not using a tetrahedral mesh, Grid3D is a rectilinear mesh.  Please read carefully the documentation on readthedocs.
